import csv
import os
import re
import sys
import urllib.request

SOURCE_URL = "https://raw.githubusercontent.com/skywind3000/ECDICT/master/ecdict.csv"
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CACHE_DIR = os.path.join(ROOT_DIR, "target", "ecdict")
CSV_PATH = os.path.join(CACHE_DIR, "ecdict.csv")
SQL_PATH = os.path.join(ROOT_DIR, "src", "main", "resources", "db", "import_ecdict_words.sql")
TARGET_COUNT = 300

BOOKS = [
    {
        "id": 1,
        "tag": "cet4",
        "label": "CET-4",
        "difficulty": "CET-4词库",
        "description": "适合大学英语四级备考的核心词汇。",
    },
    {
        "id": 2,
        "tag": "cet6",
        "label": "CET-6",
        "difficulty": "CET-6词库",
        "description": "覆盖大学英语六级阅读与写作常见词汇。",
    },
    {
        "id": 3,
        "tag": "ky",
        "label": "考研",
        "difficulty": "考研词库",
        "description": "面向考研英语阅读和写作的核心词汇。",
    },
]

WORD_RE = re.compile(r"^[a-z]{2,30}$")
HAN_RE = re.compile(r"[\u4e00-\u9fff]")


def download_if_needed() -> None:
    os.makedirs(CACHE_DIR, exist_ok=True)
    if os.path.exists(CSV_PATH) and os.path.getsize(CSV_PATH) > 1024 * 1024:
        return

    print(f"Downloading ECDICT CSV from {SOURCE_URL}")
    urllib.request.urlretrieve(SOURCE_URL, CSV_PATH)


def trim(value: str, max_length: int) -> str:
    value = (value or "").replace("\\n", "；").replace("\r", " ").replace("\n", " ")
    value = re.sub(r"\[[^\]]+\]\s*", "", value)
    value = re.sub(r"；\s*；+", "；", value)
    value = value.strip(" ；")
    while "  " in value:
        value = value.replace("  ", " ")
    return value[:max_length]


def sql_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "''")


def has_tag(row: dict[str, str], tag: str) -> bool:
    tags = set((row.get("tag") or "").lower().split())
    return tag in tags


def valid_row(row: dict[str, str]) -> bool:
    word = (row.get("word") or "").strip().lower()
    translation = row.get("translation") or ""
    return bool(WORD_RE.match(word)) and bool(translation.strip()) and bool(HAN_RE.search(translation))


def row_score(row: dict[str, str]) -> tuple[int, int, str]:
    collins = row.get("collins") or "0"
    bnc = row.get("bnc") or "999999"
    frq = row.get("frq") or "999999"
    try:
        collins_score = int(collins)
    except ValueError:
        collins_score = 0
    try:
        bnc_score = int(bnc)
    except ValueError:
        bnc_score = 999999
    try:
        frq_score = int(frq)
    except ValueError:
        frq_score = 999999
    oxford_score = 0 if row.get("oxford") else 1
    return -collins_score, oxford_score, bnc_score, frq_score, row.get("word") or ""


def read_candidates() -> list[dict[str, str]]:
    with open(CSV_PATH, "r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)
        return [row for row in reader if valid_row(row)]


def select_words(
    rows: list[dict[str, str]],
    tag: str,
    used_words: set[str],
    exclude_tags: set[str],
) -> list[dict[str, str]]:
    # Use the exam tag as the source of truth, and only avoid words that were
    # already selected for earlier books. Some higher-level word lists naturally
    # include lower-level tags, so excluding those tags too aggressively makes
    # the final list less useful.
    primary = [row for row in rows if has_tag(row, tag)]
    fallback = [row for row in rows if has_tag(row, tag)]

    selected: list[dict[str, str]] = []

    def append_candidates(candidates: list[dict[str, str]]) -> None:
        for row in sorted(candidates, key=row_score):
            word = (row.get("word") or "").strip().lower()
            if word in used_words:
                continue
            selected.append(row)
            used_words.add(word)
            if len(selected) >= TARGET_COUNT:
                return

    append_candidates(primary)
    if len(selected) < TARGET_COUNT:
        append_candidates(fallback)

    return selected


def insert_line(book_id: int, row: dict[str, str], difficulty: str) -> str:
    word = trim((row.get("word") or "").lower(), 100)
    phonetic = trim(row.get("phonetic") or "", 100)
    meaning = trim(row.get("translation") or "", 255)
    definition = trim(row.get("definition") or "", 255)
    memory_tip = trim("来源：ECDICT 开源词库", 255)

    values = [
        str(book_id),
        f"'{sql_escape(word)}'",
        f"'{sql_escape(phonetic)}'",
        f"'{sql_escape(meaning)}'",
        f"'{sql_escape(memory_tip)}'",
        f"'{sql_escape(definition)}'",
        "''",
        f"'{sql_escape(meaning)}'",
        f"'{sql_escape(difficulty)}'",
    ]
    return "  (" + ", ".join(values) + ")"


def generate_sql(selected_by_book: dict[int, list[dict[str, str]]]) -> None:
    lines: list[str] = [
        "-- Generated by scripts/import_ecdict_words.py",
        "-- Source: https://github.com/skywind3000/ECDICT",
        "SET NAMES utf8mb4;",
        "USE words_demo;",
        "",
        "DELETE FROM words WHERE book_id IN (1, 2, 3);",
        "",
    ]

    for book in BOOKS:
        book_id = book["id"]
        words = selected_by_book[book_id]
        lines.extend([
            "INSERT INTO words (",
            "  book_id, word, phonetic, meaning, memory_tip, example_text, translation_text, answer, difficulty",
            ") VALUES",
        ])
        lines.append(",\n".join(insert_line(book_id, row, book["difficulty"]) for row in words) + ";")
        lines.append("")
        lines.append(
            "UPDATE books SET "
            f"total_words = {len(words)}, "
            f"description = '{sql_escape(book['description'])}' "
            f"WHERE id = {book_id};"
        )
        lines.append("")

    with open(SQL_PATH, "w", encoding="utf-8", newline="\n") as file:
        file.write("\n".join(lines))


def main() -> int:
    download_if_needed()
    rows = read_candidates()

    used_words: set[str] = set()
    selected_by_book: dict[int, list[dict[str, str]]] = {
        1: select_words(rows, "cet4", used_words, set()),
        2: select_words(rows, "cet6", used_words, {"cet4"}),
        3: select_words(rows, "ky", used_words, {"cet4", "cet6"}),
    }

    for book in BOOKS:
        count = len(selected_by_book[book["id"]])
        if count < TARGET_COUNT:
            print(f"Only selected {count} words for {book['label']}.", file=sys.stderr)
            return 1

    generate_sql(selected_by_book)
    for book in BOOKS:
        print(f"{book['label']}: {len(selected_by_book[book['id']])} words")
    print(f"SQL written to {SQL_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
